/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.punchcafe.ai.bayesian;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}


